# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suburb', '0001_initial'),
        ('burbnews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='suburb',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='local', to='suburb.Suburb'),
        ),
    ]
