# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burbnews', '0005_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='topic_image/'),
        ),
    ]
