# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 17:58
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Residents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='residents',
            name='suburb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residency', to='suburb.Suburb'),
        ),
        migrations.AddField(
            model_name='residents',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_suburb', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='residents',
            unique_together=set([('suburb', 'user')]),
        ),
    ]
