# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suburb', '0002_auto_20180527_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
