# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 15:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suburb', '0003_resident_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_suburb', to=settings.AUTH_USER_MODEL),
        ),
    ]
