# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suburb', '0004_auto_20180527_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='suburb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residency', to='suburb.Suburb'),
        ),
    ]
