# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suburb', '0007_auto_20180527_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resident', to=settings.AUTH_USER_MODEL),
        ),
    ]
