# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 09:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suburb', '0009_auto_20180528_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='suburb',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suburb', to=settings.AUTH_USER_MODEL),
        ),
    ]
