# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suburb', '0011_auto_20180528_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suburb',
            name='location',
        ),
        migrations.AddField(
            model_name='suburb',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='suburb',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
    ]
